project_id = "xklwzkraobxetxdcysun"

[functions.access-auth]
verify_jwt = false

[functions.access-admin]
verify_jwt = false

[functions.access-agency]
verify_jwt = false

[functions.access-wallet]
verify_jwt = false

[functions.svp-proxy]
verify_jwt = false

[functions.takamol-proxy]
verify_jwt = false

[functions.svp-registration]
verify_jwt = false

[functions.svp-auth]
verify_jwt = false

[functions.test-center-owner]
verify_jwt = false
